spring:
  datasource:
    driver-class-name: org.h2.Driver
    password: password
    tomcat:
      initialSize: 20
      max-active: 20
      maxIdle: 20
    url: jdbc:h2:mem:testdb
    username: sa
logging:
  config: classpath:logback-spring.xml
  level:
    org:
      springframework:
        cache: DEBUG
    root: INFO