server:
  servlet:
   context-path: /schematenancy
  port: 8081
spring:
  application:
    name: Spring Boot Project to demonstrate Schema Tenancy in a single DB
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        globally_quoted_identifiers: true
  profiles:
    active: local